using System;
using System.Runtime.InteropServices;

namespace MyDotNet35App
{
    class Program
    {
        static void Main(string[] args)
        {
            string message = "Dotnet-bot: Welcome to using .NET Framework!";

            if (args.Length > 0)
            {
                message = String.Join(" ", args);
            }

            Console.WriteLine(GetBot(message));
            Console.WriteLine();
            Console.WriteLine("**Environment**");

            if (Environment.Version.ToString().Equals("2.0.50727.8745"))
            {
                Console.WriteLine($".NET Framework Version: 3.5");
            }
            else if (Environment.Version.ToString().Equals("4.0.30319.42000"))
            {
                Console.WriteLine($".NET Framework Version: 4.6.2");
            }
            Console.WriteLine($"CLR Version: " + Environment.Version);
            Console.ReadLine();
        }

        public static string GetBot(string message)
        {
            string bot = $"\n        {message}";
            bot += @"
    __________________
                      \
                       \
                          ....
                          ....'
                           ....
                        ..........
                    .............'..'..
                 ................'..'.....
               .......'..........'..'..'....
              ........'..........'..'..'.....
             .'....'..'..........'..'.......'.
             .'..................'...   ......
             .  ......'.........         .....
             .                           ......
            ..    .            ..        ......
           ....       .                 .......
           ......  .......          ............
            ................  ......................
            ........................'................
           ......................'..'......    .......
        .........................'..'.....       .......
     ........    ..'.............'..'....      ..........
   ..'..'...      ...............'.......      ..........
  ...'......     ...... ..........  ......         .......
 ...........   .......              ........        ......
.......        '...'.'.              '.'.'.'         ....
.......       .....'..               ..'.....
   ..       ..........               ..'........
          ............               ..............
         .............               '..............
        ...........'..              .'.'............
       ...............              .'.'.............
      .............'..               ..'..'...........
      ...............                 .'..............
       .........                        ..............
        .....

";
            return bot;
        }
    }
}
